### ISSUE TITLE
Setting debug flag with express middleware still fires network requests

### ISSUE THREAD

**Issue by tomredman** [bufferapp/buffer-js-buffermetrics#13]
Set up Analyze with:

```
app.use(buffermetricsMiddleware({
  name: 'Buffer-Analyze',
  debug: !isProduction,
  trackVisits: true
}));
```

Yet still seeing the tracking requests sent via network (although unsuccessfully, which is another issue I think). Also there are no messages in the console:
<img width="1321" alt="screen shot 2018-01-09 at 4 11 17 pm" src="https://user-images.githubusercontent.com/4225378/34743447-bda1b4e2-f557-11e7-9b43-753ce3937204.png">

**Comment by tomredman** [comment]
Hmm `isProduction` might be wrong...

**Comment by djfarrelly** [comment]
Hey @tomredman, the debug flag is only meant for the backend side of the code, specifically when it comes to sending the metric to the gRPC collector service itself. All other functions, front-end and backend should work exact the same, sort of like a "dry run" - Maybe that is a better name for that flag - What do you think?

https://github.com/bufferapp/buffer-js-buffermetrics/blob/49e7cd6e5778f1c58b09cd031185e4c7f918305b/index.js#L82-L87

https://github.com/bufferapp/buffer-js-buffermetrics/blob/49e7cd6e5778f1c58b09cd031185e4c7f918305b/index.js#L99-L100

**Comment by tomredman** [comment]
Ah, gotcha thanks @djfarrelly! I think `debug` is valid. I think I was confused where `verifyMessage` was still triggering the client actions. As long as this is working as designed I'm good with this!

**Comment by djfarrelly** [comment]
Sounds good @tomredman - I've been the only consumer of this library, so lots of my design assumptions could be off. I'd love any feedback or suggestions you or your team had to make this better! Still pre 1.0, I'm considering anything to be up for change!
