### ISSUE TITLE
Ignore actions that aren't key wrapped / provide actions to exclude

### ISSUE THREAD

**Issue by tomredman** [bufferapp/buffer-js-buffermetrics#15]
The library still tracks actions even if they're not keywrapped with __ to break them apart. There are a couple actions I'd like to exclude from tracking (performance/loading/fetching stuff). Would be cool to be able to selectively exclude some actions.

**Comment by tomredman** [comment]
Submitted PR for this here: https://github.com/bufferapp/buffer-js-buffermetrics/pull/16

**Comment by djfarrelly** [comment]
#16 now merged
